### ISSUE TITLE
regarding improvements in UI of startup_namer app 

### ISSUE THREAD

**Issue by Ramanpreet6262** [sagarchoudhary96/Flutter-Examples#3]
I will make some changes in Appbar 
Pls assign it to me...

**Comment by nikhilbansal97** [comment]
@Ramanpreet6262 You can work on another sample app that can benefit other devs looking for some code samples and work on Appbar on that.

**Comment by Ramanpreet6262** [comment]
ok

**Comment by Ramanpreet6262** [comment]
I am closing this issue
